### ISSUE TITLE
 'X-Frame-Options' to 'SAMEORIGIN'

### ISSUE THREAD

**Issue by pankaj45** [Instamojo/instamojo-php#17]
For remote checkout, the browser is displaying error 
refused to display 'https://www.instamojo.com/.../?intent=buy&checkout=remote' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

**Comment by ashwch** [comment]
@pankaj45 Can you share the full link?

**Comment by saikumark** [comment]
@pankaj45 , Hello, I am facing similar issue, can you share the fix applied?
