### ISSUE TITLE
Array to String conversion - Instamojo.php line no. 298

### ISSUE THREAD

**Issue by rebootcode** [Instamojo/instamojo-php#33]
Hello, I am using it with Laravel and while running the code. Create payment request is successful but when i check the payment status, it returns

`Array to String Conversion`

Debugging more , I found it is line no. 298 in instamojo.php

Could you please check, what am i doing wrong.

**Comment by ashwch** [comment]
@rebootcode Can you share your code that is resulting in this error? Note that `$id` should be a string not an array.

**Comment by rebootcode** [comment]
This is what, I am exactly doing :- 

`
$app->get('instamojo/payment', function() {
$api = new Instamojo\Instamojo('My_API_Key', 'My_Auth_Token');
try {
    $response = $api->paymentRequestCreate(array(
        "purpose" => "FIFA 16",
        "amount" => "3499",
        "send_email" => true,
        "email" => "foo@test.com",
        "redirect_url" => "http://www.example.local/instamojo/payment/status"
        ));
    print_r($response);
}
catch (Exception $e) {
    print('Error: ' . $e->getMessage());
}
});
`
and to get the status :- 

`
$app->get('instamojo/payment/status', function() {
$api = new Instamojo\Instamojo('My_API_Key', 'My_Auth_Token');
try {
    $response = $api->paymentRequestStatus(['payment_id_received_from_top']);
    print_r($response);
}
catch (Exception $e) {
    print('Error: ' . $e->getMessage());
}    
});
`

from second route "instamojo/payment/status" , I am getting error 

`Array to string converstion`

**Comment by ashwch** [comment]
The `[]` are just placeholders, don't include them. 

Use: `paymentRequestStatus('payment_id_received_from_top')`

**Comment by rebootcode** [comment]
Oh! Got it.

Thanks
