### ISSUE TITLE
Rename the class file name

### ISSUE THREAD

**Issue by karthik-code** [Instamojo/instamojo-php#35]
It's not working on the linux server. Case sensitivity issue.
Rename the file instamojo-php/src/instamojo.php to instamojo-php/src/**Instamojo.php**

**Comment by ashwch** [comment]
@karthik-code Help us in reproducing the issue.

**Comment by karthik-code** [comment]
Instamojo/Instamojo class not found error occurred while I am running the code on production server (Cent OS). But the same code working fine in local development system (Windows 10). 
After renaming the file at server,, issue resolved.

**Comment by neokio** [comment]
@karthik-code THANK YOU. I wasted an hour trying to figure this out, until I read your post. This API wrapper is fundamentally broken on any case-sensitive OS (linux).
