### ISSUE TITLE
Instamojo Library for GoLang

### ISSUE THREAD

**Issue by rebootcode** [Instamojo/instamojo-php#41]
I am looking for Instamojo Library for Golang.

**Comment by ashwch** [comment]
Doesn't make any sense to create an issue on PHP wrapper. Please shoot an email to support@instamojo.com for such requirements or issues.

We don't have an immediate plan for adding a Go wrapper. But if you want to contribute we would help you out if you face any issues.

We sort of have a Go wrapper around our Orders API, it is being used it our Sample SDK server. You can find its code here: https://github.com/Instamojo/sample-sdk-server
