### ISSUE TITLE
incorrect parameter due to typo in line 143

### ISSUE THREAD

**Issue by mtrajan** [Instamojo/instamojo-php#5]
There is an incorrect parameter upload_file in  instamojo.php on line 143,   https://github.com/Instamojo/instamojo-php/blob/master/instamojo.php
 
if($link['file_upload']) {
$file_upload_json = $this->uploadFile($link['upload_file']);

Both above lines should have the same value 'file_upload'

**Comment by ashwch** [comment]
Thanks @mtrajan. Fixed in [255eefd](https://github.com/ashwch/instamojo-php/commit/255eefd68ffee92f1eab718e73aca79f863d9531).

**Comment by mtrajan** [comment]
cool ! thanks

Regards,
Rajan
--------------------------------------------
Q: Why is this email five sentences or less?
A: http://five.sentenc.es

On Fri, Apr 10, 2015 at 1:14 PM, Ashwini Chaudhary <notifications@github.com
